name: Release

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: 
  push:
    branches:
      - "main"

jobs:
  macos-arm64:
    name: "🍎 deno_v8_snapshot_macos_arm64"
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: true
      - run: |
          set -e

          brew install llvm lld cmake protobuf make gcc
          export PATH="/opt/homebrew/opt/llvm/bin:$PATH"

          source .github/scripts/utils/install-rust.bash
          source .github/scripts/utils/install-protobuf.bash \
            https://github.com/protocolbuffers/protobuf/releases/download/v25.3/protoc-25.3-osx-aarch_64.zip

          rustup target add aarch64-apple-darwin

          cd deno && cargo build --release --target aarch64-apple-darwin
      - run: |
          cargo build --release
          cargo publish --package deno_v8_snapshot_macos_arm64 --token $CRATES_IO_API_TOKEN
        env:
          CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-deno-v8-snapshot:
    name: "🔄 deno_v8_snapshot"
    runs-on: ubuntu-latest
    needs: [macos-arm64]
    steps:
      - uses: actions/checkout@v4
      - env:
          CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
        run: |
          cargo publish --package deno_v8_snapshot --token $CRATES_IO_API_TOKEN
