name: Release

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: 
  push:
    branches:
      - "main"

jobs:
  macos-arm64:
    name: "🍎 MacOS ARM64"
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: |
          set -e

          brew install llvm cmake protobuf make gcc

          source .github/scripts/utils/install-rust.bash
          source .github/scripts/utils/install-protobuf.bash \
            https://github.com/protocolbuffers/protobuf/releases/download/v25.3/protoc-25.3-osx-aarch_64.zip

          rustup target add aarch64-apple-darwin

          cd deno
          cargo build --release --target aarch64-apple-darwin
      - run: |
          cargo publish --package deno_embed_macos_arm64 --token $CRATES_IO_API_TOKEN
        env:
          CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-deno-embed:
    name: "🔄 Publish deno_embed"
    runs-on: ubuntu-latest
    needs: [macos-arm64]
    steps:
      - uses: actions/checkout@v4
      - env:
          CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
        run: |
          cargo publish --package deno_embed --token $CRATES_IO_API_TOKEN
